export const FETCH_SWAPI_TYPES_STARTED = 'FETCH_SWAPI_TYPES_STARTED';
export const FETCH_SWAPI_TYPES_SUCCESS = 'FETCH_SWAPI_TYPES_SUCCESS';
export const FETCH_SWAPI_TYPES_FAILED = 'FETCH_SWAPI_TYPES_FAILED';
export const UPDATE_SEARCH_TYPE = 'UPDATE_SEARCH_TYPE';
export const UPDATE_SEARCH_QUERY = 'UPDATE_SEARCH_QUERY';
export const SEARCH_SWAPI_STARTED = 'SEARCH_SWAPI_STARTED';
export const SEARCH_SWAPI_SUCCESS = 'SEARCH_SWAPI_SUCCESS';
export const SEARCH_SWAPI_FAILED = 'SEARCH_SWAPI_FAILED';
