export const LOAD_SWAPI = 'LOAD_SWAPI';
export const GET_PEOPLE = 'GET_PEOPLE';

export const SWAPI_SEARCH_FAILED = 'SWAPI_SEARCH_FAILED';
export const SWAPI_SEARCH_STARTED = 'SWAPI_SEARCH_STARTED';
export const SWAPI_SEARCH_SUCCESS = 'SWAPI_SEARCH_STARTED';
export const SWAPI_LOAD_MORE_STARTED = 'SWAPI_LOAD_MORE_STARTED';
export const SWAPI_LOAD_MORE_SUCCESS = 'SWAPI_LOAD_MORE_SUCCESS';
export const SWAPI_LOAD_MORE_FAILED = 'SWAPI_LOAD_MORE_FAILED';
